= Savage of Legend
:toc: left
:toc-title: Table des matières
:toclevels: 2



== Avant propos

Ce document est une adaptation du jeu de rôle _Earthdawn_ vers le système de jeu générique de _Savage Worlds_.
Les licences _Earthdawn_ et _Savage Worlds_ appartiennent à leurs propriétaires respectifs.
Ce document part du principe que le lecteur connait l'univers et les principes de jeu d'_Earthdawn_,
et dispose de la VF de _Savage Worlds_ sous la main.

Outre les sources déjà citées, ce document est basé en partie sur
http://www.rollenspiel-almanach.de/download/Savage_Earthdawn_3.0_public.pdf[Savage Dawn 3.0], de Markus Finster,
que je n'ai pas repris car j'avais besoin de règles en français, et que je désirais remanier pas mal de points
(en gros, j'ai pris comme point de départ son interaction entre Karma et les disciplines et talents en tant qu'Atouts).
Pour davantage de détails sur mes motivations, j'ai planqué ça <<design_notes,tout à la fin>>,
histoire de pas commencer par vous assomer avec mes états d'âme.

Bonne lecture !





[[build_your_legend]]
== Bâtir sa Légende

Les points de Légende permettent d'acheter des améliorations de personnage.
Les coûts de ces améliorations sont comme-ci :

* Choisir un nouvel <<edges,Atout>> (2 points de Légende)
* Augmenter une <<skills,Compétence>> dont la valeur est égale ou supérieure au Trait associé (2 points de Légende)
* Augmenter une <<skills,Compétence>> dont la valeur est inférieure au Trait associé (1 point de Légende)
* Prendre une nouvelle <<skills,Compétence>> à d4 (1 point de Légende)
* Prendre une nouvelle <<skill_knowledge,Connaissance>> (1 point de Légende)
* Augmenter un Attribut (2 points de Légende, une seule fois par <<ranks,Rang>>)

=== Création de personnage
La création du personnage suit la procédure habituelle (_Savage Worlds_ pages 26,72), avec les ajustements suivants :

1. Choix de la race
2. Choix des Traits
** Le personnage débute avec un d4 dans chaque Attribut et peut les augmenter 5 fois
** Le personnage dispose de 15 <<build_your_legend,points de Légende>> à répartir dans ses <<skills,Compétences>>
** Le personnage obtient gratuitement une <<skill_knowledge,Compétence artisanale et artistique>> de son choix
** Le personnage parle automatiquement la <<skill_knowledge,Langue (nain)>> +
   Un personnage <<race_dwarves,nain>> obtient une autre <<skill_knowledge,Connaissance>> de son choix à la place
** N'oubliez pas de calculer le Charisme, l'Allure, la Parade, la Résistance du personnage,
   mais aussi sa <<karma,Réserve de Karma>> (égale à son <<ranks,Cercle>>)
   ainsi que son maximum de <<blood_magic,Dommages permanents>> (égal à sa Résistance)
3. Choix de la <<disciplines,Discipline>>
4. Choix des Atouts et Handicaps
** Un Handicap Majeur rapport 2 <<build_your_legend,points de Légende>>
** Un Handicap Mineur rapport 1 <<build_your_legend,point de Légende>>
5. Achat de l'équipement : le personnage dispose de 120 pièces d'argent
6. Rédaction de l'histoire personnelle

Un personnage nouvellement créé est de <<ranks,Cercle>> 1.

=== Progression du personnage
Tous les 5 XP gagnés, un personnage gagne un Cercle.
Il bénéficie alors de 2 <<build_your_legend,points de Légende>>.

Tous les 20 XP gagnés, le personnage peut passer au Rang supérieur.
Pour que ce passage de Rang soit validé, un adepte doit trouver un instructeur membre de sa discipline.
Cet instructeur doit être d'un Cercle plus élevé que celui du personnage, et accepter de l'entraîner pendant 40H, réparties sur un mois maximum.
Cet entraînement n'est pas nécessaire pour les adeptes ayant atteint le Rang de Maître ou de Légende.

[[ranks]]
.Cercle et Rang
[width=40%, options="header"]
|===
|Rang|Nom       |XP    |Cercle |Équivalent 

| 1  |Novice     | 0-19 | 1-4   |Novice     
| 2  |Compagnon  |20-39 | 5-8   |Aguerri    
| 3  |Gardien    |40-59 | 9-12  |Vétéran    
| 4  |Maître     |60-79 |13-16  |Héroïque   
| 5  |Légende    | 80+  | 17+   |Légendaire 
|===

Un adepte d'un Rang au moins égal à celui de Compagnon peut se passer d'instructeur vivant et invoquer un maître fantôme.
Chaque rituel du maître fantôme a une durée d'une nuit.
Le personnage fait un jet d'Âme.
Une réussite invoque le maître fantôme pour toute la nuit.
Un échec ouvre un portail sur l'espace astral pour une durée de (5 - Rang) minutes.



[[races]]
== Races

[[race_elves]]
=== Elfes
*Agile :* Un elfe débute avec d6 en Agilité au lieu de d4. +
*Vision nocturne :* Un elfe ignore les malus pour les obscurités Légère et Forte.

[[race_humans]]
=== Humains
*Atout :* Un humain débute avec un <<edges,Atout>> gratuit de leur choix, qui peut être l'Atout <<edge_versatility,Polyvalence>>. +
*Potentiel :* Un humain débute avec 1 <<build_your_legend,point de Légende>> supplémentaire.

[[race_dwarves]]
=== Nains
*Lent :* Un nain a une Allure de 5. +
*Robuste :* Un nain débute avec d6 en Vigueur au lieu de d4. +
*Endurant :* Un nain bénéficie d'un bonus de +2 pour résister aux effets négatifs de l'environnement (chaleur, froid, pression, ...), ainsi que pour résister à la maladie et au poison. +
*Vision thermographique :* Un nain divise de moitié les malus (arrondir à l'inférieur) dus à une luminosité faible.

[[race_obsidmens]]
=== Obsidiens
*Comportement :* Un obsidien débute avec les Handicaps suivants : Loyal (Mineur) (_Savage Worlds_ page 50), Pacifiste (Mineur) et Prudent (Mineur) (_Savage Worlds_ page 52). +
*Étranger :* Un obsidien subit un malus de -2 à son Charisme. +
*Taille :* La Taille d'un obsidien est de +1 (_Savage Worlds_ page 242). +
*Très lent :* Un obsidien a une Allure de 3 (dé de course d4). +
*Très puissant :* Un obsidien débute avec d8 en Force. +
*Très robuste :* Un obsidien débute avec d8 en Vigueur. +
*Vœu :* Un obsidien ne peut porter que des armures vivantes.

[[race_orks]]
=== Orks
*Puissant :* Un ork débute avec d6 en Force au lieu de d4. +
*Vision nocturne :* Un ork ignore les malus pour les obscurités Légère et Forte.

[[race_windlings]]
=== Sylphelins
*Curieux :* Un sylphelin débute avec le Handicap Curieux (Majeur) (_Savage Worlds_ page 49). +
*Taille :* La Taille d'un sylphelin est de -1 (_Savage Worlds_ page 242). +
*Faible :* La Force d'un sylphelin ne peut pas dépasser d6. +
*Vol :* Un sylphelin peut voler à son Allure normale, et même « courir » lorsqu'il vole (_Savage Worlds_ page 243).
Il lui coûte 2 points d'Allure pour monter d'une case.
Un sylphelin peut voler au maximum 15 minutes d'affilée.
Il doit se reposer 1 minute pour récupérer de chaque minute passée en vol. +
En vol, l'Allure d'un sylphelin est de 10. +
Au sol, l'Allure d'un sylphelin est de 4. +
*Sensibilité astrale :* Un sylphelin peut percevoir l'espace astral, comme décrit par le talent <<talent_astral_sight,Vision astrale>>.
Un sylphelin n'a pas besoin de dépenser de points de Karma pour activer cette faculté. +
*Créature magique :* Un sylphelin débute avec l'Atout <<edge_karma_affinity,Régénération de Karma>>.

[[race_trolls]]
=== Trolls
*Taille :* La Taille d'un troll est de +1 (_Savage Worlds_ page 242). +
*Puissant :* Un troll débute avec d6 en Force au lieu de d4. +
*Robuste :* Un troll débute avec d6 en Vigueur au lieu de d4. +
*Vision thermographique :* Un troll divise de moitié les malus (arrondir à l'inférieur) dus à une luminosité faible. +
*Katorr, kat'ral, katera :* Un troll des montagnes débute avec le Handicap Rancunier (Majeur) (_Savage Worlds_ page 52).
Un troll des plaines débute avec les Handicaps Deux mains Gauches (_Savage Worlds_ page 49) et Rancunier (Mineur) (_Savage Worlds_ page 52).
Tous les trolls débutent avec le Handicap Code d'Honneur (Majeur) (_Savage Worlds_ page 49).

[[race_tskrangs]]
=== T'skrangs
*Aquatique :* Un t'skrang ne peut pas se noyer dans l'eau, se déplace à une Allure égal à son dé de Natation, et débute avec d6 en <<skill_swimming,Natation>>. +
*Attaque caudale :* Un t'skrang peut frapper à l'aide de sa queue à For+d6 de dégâts.

[[skills]]
== Compétences

[[skill_melee_weapons]]
=== Armes de mêlée (Agilité)
Nouveau nom de la Compétence *Combat* (_Savage Worlds_ page 40), son usage est en tout point identique.

[[skill_ranged_weapons]]
=== Armes à distance (Agilité)
Regroupe tous les usages des anciennes Compétences de *Lancer* (_Savage Worlds_ page 44) et de *Tir* (_Savage Worlds_ page 46).

[[skill_knowledge]]
=== Connaissance

Une Connaissance n'a pas de dé associé : soit un personnage la possède, soit il ne la possède pas.

Une Connaissance permet au personnage qui la possède de tenter une action qui sort de l'usage habituel d'un Trait donné.
Voici quelques exemples :

* Une *Connaissance pure* correspond en quelques sortes à l'ancienne Compétence *Connaissance* (_Savage Worlds_ page 41). Elle permet de tenter des tests de Culture générale ayant trait à ces sujets (_Savage Worlds_ page 40). +
  Voici une liste non exhaustive de Connaissances que peut posséder un personnage : _Alchimie et potions_, _Animaux et créatures sauvages_, _Armes anciennes_, _Histoire de Barsaive_, _Batailles_, _Botanique_, _Châtiment_, connaissance d'une race, d'une culture ou d'une région au choix, _Horreurs_, _Légendes et héros_, _Thérans_.
* Une *Langue* est aussi une Connaissance.
  Un personnage qui dispose d'une Connaissance de Langue particulière peut s'exprimer suffisamment clairement dans cette langue pour communiquer via les <<skills,Compétences>> d'<<skill_intimidation,Intimidation>>, de <<skill_persuasion,Persuasion>>, de <<skill_investigation,Renseignements>> et de <<skill_taunt,Sarcasmes>> sans aucun malus.
* Certaines Compétences du système de base de _Savage Worlds_ peuvent être reprises en tant que *Connaissance générale*. Ce sont : _Conduite_ (d'attelages), _Jeu_, _Pistage_, _Navigation_. +
  Le Trait dont on se sert pour résoudre une action les concernant dépend des circonstances.
  Par défaut, l'Attribut de base de l'ancienne Compétence correspondante peut être utilisé.
* Une *Compétence artisanale et artistique* est aussi une Connaissance.
  Quelques exemples : _Art du conteur_, _Broderie_, _Chant_, _Danse_, _Gravures runiques_, _Musique_, _Peinture_, _Sculpture_, _Tatouages_, travailler un matériau au choix (tel que le bois, l'os, la pierre ou le cristal vivant) ... +
  Le Trait dont on se sert pour décider de la qualité d'une création artistique varie entre Âme, Agilité et Intellect.

[[skill_lockpicking]]
=== Crochetage (Agilité)
Fonctionnement inchangé (_Savage Worlds_ page 42).

[[skill_stealth]]
=== Discrétion (Agilité)
Fonctionnement inchangé (_Savage Worlds_ page 42).

[[skill_riding]]
=== Équitation (Agilité)
Fonctionnement inchangé (_Savage Worlds_ page 43).

[[skill_climbing]]
=== Escalade (Force)
Fonctionnement inchangé (_Savage Worlds_ page 43).

[[skill_repair]]
=== Forge (Intellect)
Nouveau nom de la Compétence *Réparation* (_Savage Worlds_ page 45), son usage est en tout point identique.

[[skill_spellcasting]]
=== Incantation (Intellect)
Cette compétence est indispensable à tout lanceur de sorts.
Elle est utilisée dans les actions magiques suivantes :

* tisser des <<thread_weaving,filaments de sorts>>
* <<spell_casting,incanter>> (lancer) un sort
* <<reattuning,réharmoniser>> une matrice de sorts à la va-vite

Voir la section <<thread_magic,Magie des sorts>> pour davantage de détails.

[[skill_intimidation]]
=== Intimidation (Âme)
Fonctionnement inchangé (_Savage Worlds_ page 43).

[[skill_summoning]]
=== Invocation (Âme)
*Prérequis :* <<talent_summoning,Invocation>>

Cette compétence permet d'invoquer des esprits.

Voir la section <<summoning,Invocation>> pour davantage de détails.

[[skill_air_sailing]]
=== Manœuvre aérienne (Âme)
Cette Compétence fonctionne de manière similaire aux anciennes Compétences *Navigation* (_Savage Worlds_ page 44) ou *Pilotage* (_Savage Worlds_ page 45).
Cependant, l'usage est ici de manœuvrer un navire aérien.

[[skill_swimming]]
=== Natation (Agilité)
Fonctionnement inchangé (_Savage Worlds_ page 44).

[[skill_notice]]
=== Perception (Intellect)
Fonctionnement inchangé (_Savage Worlds_ page 44).

[[skill_persuasion]]
=== Persuasion (Âme)
Fonctionnement inchangé (_Savage Worlds_ page 44).

[[skill_investigation]]
=== Renseignements (Intellect)
Regroupe tous les usages des anciennes Compétences de *Recherche* et de *Réseaux* (_Savage Worlds_ page 45).
Renseignements n'est pas modifiée par le *Charisme* d'un personnage.

[[skill_taunt]]
=== Sarcasmes (Intellect)
Nouveau nom de la Compétence *Sarcasme* (_Savage Worlds_ page 40), son usage est en tout point identique.

[[skill_healing]]
=== Soins (Intellect)
Fonctionnement inchangé (_Savage Worlds_ page 46).

[[skill_survival]]
=== Survie (Intellect)
Fonctionnement inchangé (_Savage Worlds_ page 46).





[[karma]]
== Karma

Un adepte ne gagne aucun Jeton au début d'une session de jeu.
À la place, il gagne un nombre de points de Karma égal à la taille de sa réserve de Karma.
La taille de la réserve de Karma d'un adepte est égale à son <<ranks,Cercle>>.

Un point de Karma peuvent être dépensé pour :

* Obtenir un bénéfice identique à celui d'un Jeton (_Savage Worlds_ page 106).
* Obtenir un bonus de +2 à certains jets, dépendant de la <<disciplines,discipline>> du personnage.
  Pour un jet donné, un maximum d'un seul point de Karma peut être utilisé de cette manière.

Une seule fois par jour, un adepte peut effectuer un rituel karmique propre à sa discipline.
Ce rituel lui permet de regagner un point de Karma.





[[disciplines]]
== Disciplines

Chaque discipline est un Atout professionel (_Savage Worlds_ page 63).
Un personnage obtient une discipline gratuitement à sa création.
Avec l'accord du MJ, un joueur désirant jouer un non-adepte peut échanger sa discipline contre un autre Atout.

Avec l'accord du MJ, un personnage peut acquérir une Discipline après la création de personnage.
Il doit l'acheter avec des <<build_your_legend,points de Légende>>.
Un adepte peut posséder plusieurs disciplines, jusqu'à une limite d'une par <<ranks,Rang>>.
Posséder plusieurs disciplines n'accroit pas la taille de la <<karma,réserve de Karma>> d'un personnage.



[[discipline_archer]]
=== Archer
*Prérequis :* <<ranks,Novice>>, <<skill_ranged_weapons,Armes à distance>> d8+

Un Archer acquiert l'atout Vigilance.

Un Archer peut utiliser un point de Karma dans le cadre d'un jet d'<<skill_ranged_weapons,Armes à distance>>.

*Talents de discipline :* <<talent_direction_arrow,Flèche de direction>>, <<talent_flame_arrow,Flèche de feu>>, <<talent_true_shot,Tir infaillible>>, <<talent_multishot,Tir multiple>>.



[[discipline_weaponsmith]]
=== Armurier
*Prérequis :* <<ranks,Novice>>, Âme d6+, <<skill_repair,Forge>> d6+

Le Charisme d'un Armurier est augmenté de 2.
Il ne doit cependant jamais mentir, et toujours tenir sa parole, sous peine de perdre ce bénéfice.

Un Armurier peut utiliser un point de Karma dans le cadre d'un jet de <<skill_repair,Forge>> ou de <<skill_investigation,Renseignements>>.

*Talents de discipline :* <<talent_temper_self,Endurcissement>>, <<talent_forge_item,Forgeage>>, <<talent_item_history,Histoire des objets>>, <<talent_spot_armor_flaw,Repérage du défaut de la cuirasse>>



[[discipline_cavalryman]]
=== Cavalier
*Prérequis :* <<ranks,Novice>>, Âme d6+, <<skill_riding,Équitation>> d6+

Quand un Cavalier combat sur sa monture, il utilise sa Compétence la plus haute entre <<skill_melee_weapons,Armes de mêlée>> et <<skill_riding,Équitation>>, au lieu de la plus basse (_Savage Worlds_ pages 43,122).

Un Cavalier peut utiliser un point de Karma dans le cadre d'un jet d'<<skill_riding,Équitation>>, ou d'un jet effectué par sa monture.

*Talents de discipline :* <<talent_fearsome_charge,Charge terrifiante>>, <<talent_mount_attack,Fureur animale>>, <<talent_mount_durability,Longévité (monture)>>, <<talent_empathic_command,Ordre empathique>>



[[discipline_horror_stalker]]
=== Chasseur d'Horreurs
*Prérequis :* <<ranks,Novice>>, Âme d10+, Vigueur d8+, <<skill_melee_weapons,Armes de mêlée>> d8+

Un Chasseur d'Horreurs obtient le talent <<talent_bear_mark,Résistance à la marque>>.

Un Chasseur d'Horreurs peut utiliser un point de Karma dans le cadre d'un jet d'<<skill_melee_weapons,Armes de mêlée>> ou de dégats effectués au cours d'un combat contre une Horreur ou une création d'Horreur.

*Talents de discipline :* <<talent_temper_self,Endurcissement>>, <<talent_spot_armor_flaw,Repérage du défaut de la cuirasse>>, <<talent_life_check,Ultime sursaut>>, <<talent_astral_sight,Vision astrale>>



[[discipline_scout]]
=== Éclaireur
*Prérequis :* <<ranks,Novice>>, <<skill_notice,Perception>> d6+

Un Éclaireur ajoute +2 à ses jets de <<skill_stealth,Discrétion>>, <<skill_notice,Perception>>, <<skill_investigation,Renseignements>> et <<skill_survival,Survie>>.
Ces bonus ne s'appliquent qu'en milieu sauvage.

Un Éclaireur peut utiliser un point de Karma dans le cadre d'un jet de <<skill_notice,Perception>> ou de <<skill_survival,Survie>>.

*Talents de discipline :* <<talent_chameleon,Caméléon>>, <<talent_avoid_blow,Esquive>>, <<talent_trap_initiative,Esquive des pièges>>, <<talent_astral_sight,Vision astrale>>



[[discipline_sky_raider]]
=== Écumeur du ciel
*Prérequis :* <<ranks,Novice>>, Force d6+, <<skill_intimidation,Intimidation>> d6+

Un Écumeur du ciel obtient un bonus de +2 à tous ses jets de <<skill_air_sailing,Manœuvre aérienne>>.

Un Écumeur du ciel utiliser un point de Karma dans le cadre d'un jet d'<<skill_intimidation,Intimidation>>, de Force, ou de n'importe quel jet effectué durant un combat de masse ayant lieu à bord d'un navire aérien.

*Talents de discipline :* <<talent_great_leap,Bondissement>>, <<talent_crushing_blow,Broyage>>, <<talent_fireblood,Sang de feu>>, <<talent_wind_catcher,Vol plané>>



[[discipline_elementalist]]
=== Élémentaliste
*Prérequis :* <<ranks,Novice>>, Âme d6+, <<skill_survival,Survie>> d6+

Un Élémentaliste obtient l'Atout <<edge_arcane_magic,Arcanes (Magie)>>.

Un Élémentaliste peut utiliser un point de Karma dans le cadre d'un jet de <<skill_survival,Survie>>.

*Talents de discipline :* <<talent_unshakeable_earth,Enracinement>>, <<talent_summoning,Invocation (Élémentaires)>>, <<talent_spell_matrix,Matrice de sorts>>, <<talent_astral_sight,Vision astrale>>



[[discipline_warrior]]
=== Guerrier
*Prérequis :* <<ranks,Novice>>, <<skill_melee_weapons,Armes de mêlée>> d8+

Un Guerrier obtient un bonus de +1 à tous ses jets de dégâts au corps à corps.

Un Guerrier peut utiliser un point de Karma dans le cadre d'un jet d'<<skill_melee_weapons,Armes de mêlée>> ou de Connaissance (Batailles).

*Talents de discipline :* <<talent_crushing_blow,Broyage>>, <<talent_temper_self,Endurcissement>>, <<talent_wood_skin,Peau de bois>>, <<talent_life_check,Ultime sursaut>>



[[discipline_illusionist]]
=== Illusionniste
*Prérequis :* <<ranks,Novice>>, Intellect d6+, <<skill_notice,Perception>> d6+

Un Illusioniste obtient l'Atout <<edge_arcane_magic,Arcanes (Magie)>>.

Un Illusionniste peut utiliser un point de Karma dans le cadre d'un jet de <<skill_persuasion,Persuasion>>.

*Talents de discipline :* <<talent_dead_fall,Fausse mort>>, <<talent_false_sight,Faux semblants>>, <<talent_spell_matrix,Matrice de sorts>>, <<talent_astral_sight,Vision astrale>>



[[discipline_swordmaster]]
=== Maître d'armes

*Prérequis :* <<ranks,Novice>>, <<skill_melee_weapons,Armes de mêlée>> d6+, <<skill_taunt,Sarcasmes>> d6+

Le Charisme d'un Maître d'armes est augmenté de 2.

Un Maître d'armes peut utiliser un point de Karma dans le cadre d'un jet d'<<skill_melee_weapons,Armes de mêlée>> ou de <<skill_taunt,Sarcasmes>>.

*Talents de discipline :* <<talent_acrobatic_strike,Attaque acrobatique>>, <<talent_avoid_blow,Esquive>>, <<talent_maneuver,Dérobade>>, <<talent_winning_smile,Sourire ravageur>>



[[discipline_beastmaster]]
=== Maître des animaux

*Prérequis :* <<ranks,Novice>>, Vigueur d6+, <<skill_survival,Survie>> d6+

Les animaux n'attaquent pas le personnage, à moins qu'il ne les attaque en premier lieu ou qu'ils ne soient enragés pour une raison quelconque.

De plus, si un Maître des animaux passe un minimum de 10 minutes en compagnie d'un animal dont l'attitude envers lui est Neutre ou meilleure, cet animal peut s'attacher à lui et devenir son compagnon, si le Maître des animaux le désire.
Un compagnon animal accompagne fidèlement le personnage et a une attitude Serviable envers lui.
Au même moment, un Maître des animaux peut s'attacher à un nombre d'animaux maximum égal à son <<ranks,Rang>>.

Un Maître des animaux peut utiliser un point de Karma dans le cadre d'un jet effectué par un de ses compagnons animaux.

*Talents de discipline :* <<talent_great_leap,Bondissement>>, <<talent_chameleon,Caméléon>>, <<talent_claw_shape,Griffes>>, <<talent_animal_possession,Possession animale>>



[[discipline_air_sailor]]
=== Navigateur aérien
*Prérequis :* <<ranks,Novice>>, Agilité d6+, <<skill_air_sailing,Manœuvre aérienne>> d6+

Un Navigateur aérien obtient un bonus de +2 à tous ses jets de <<skill_air_sailing,Manœuvre aérienne>>.

Un Navigateur aérien peut utiliser un point de Karma dans le cadre d'un jet de <<skill_air_sailing,Manœuvre aérienne>>, ou de n'importe quel jet effectué durant un combat de masse ayant lieu à bord d'un navire aérien.

*Talents de discipline :* <<talent_acrobatic_strike,Attaque acrobatique>>, <<talent_great_leap,Bondissement>>, <<talent_avoid_blow,Esquive>>, <<talent_wind_catcher,Vol plané>>




[[discipline_nethermancer]]
=== Nécromancien
*Prérequis :* <<ranks,Novice>>, Âme d6+, <<skill_intimidation,Intimidation>> d6+

Un Nécromancien obtient l'Atout <<edge_arcane_magic,Arcanes (Magie)>>.

Un Nécromancien peut utiliser un point de Karma dans le cadre d'un jet d'<<skill_intimidation,Intimidation>>.

*Talents de discipline :* <<talent_lionheart,Cœur de lion>>, <<talent_summoning,Invocation (Morts)>>, <<talent_spell_matrix,Matrice de sorts>>, <<talent_astral_sight,Vision astrale>>



[[discipline_wizard]]
=== Sorcier
*Prérequis :* <<ranks,Novice>>, Intellect d6+, <<skill_investigation,Renseignements>> d6+

Un Sorcier obtient l'Atout <<edge_arcane_magic,Arcanes (Magie)>>.

Un Sorcier peut utiliser un point de Karma dans le cadre d'un jet de <<skill_investigation,Renseignements>>.

*Talents de discipline :* <<talent_evidence_analysis,Analyse des indices>>, <<talent_spell_matrix,Matrice de sorts>>, <<talent_book_memory,Mémoire des livres>>, <<talent_astral_sight,Vision astrale>>



[[discipline_troubadour]]
=== Troubadour
*Prérequis :* <<ranks,Novice>>, Intellect d6+, <<skill_persuasion,Persuasion>> d6+

Le Charisme d'un Troubadour est augmenté de 2.

Un Troubadour peut utiliser un point de Karma dans le cadre d'un jet de <<skill_persuasion,Persuasion>>, de <<skill_taunt,Sarcasmes>> ou de <<skill_investigation,Renseignements>>.

*Talents de discipline :* <<talent_emotion_song,Chant d'émotion>>, <<talent_speak_language,Glossolalie>>, <<talent_item_history,Histoire des objets>>, <<talent_winning_smile,Sourire ravageur>>



[[discipline_thief]]
=== Voleur
*Prérequis :* <<ranks,Novice>>, Agilité d6+, <<skill_stealth,Discrétion>> d6+

Un Voleur ajoute +2 à tous ses jets de <<skill_stealth,Discrétion>>.

Un Voleur peut utiliser un point de Karma dans le cadre d'un jet de <<skill_lockpicking,Crochetage>> ou de <<skill_stealth,Discrétion>>.

*Talents de discipline :* <<talent_surprise_strike,Attaque surprise>>, <<talent_avoid_blow,Esquive>>, <<talent_trap_initiative,Esquive des pièges>>, <<talent_dead_fall,Fausse mort>>





[[talents]]
== Talents

Les talents sont des atouts étranges.
Tout personnage peut acquérir un talent du moment qu'il en satisfait les prérequis,
que ce talent figure dans la liste de ses talents de <<disciplines,discipline>>,
et qu'il trouve quelqu'un pour le lui apprendre.

[[talent_evidence_analysis]]
=== Analyse des indices
*Prérequis :* <<ranks,Compagnon>>, <<skill_notice,Perception>> d6+

Le personnage peut dépenser un point de Karma pour obtenir un bonus à un jet de <<skill_notice,Perception>> égal à son <<ranks,Rang>>.

[[talent_acrobatic_strike]]
=== Attaque acrobatique
*Prérequis :* <<ranks,Compagnon>>, Agilité d8+, <<skill_melee_weapons,Armes de mêlée>> d8+

Le personnage peut dépenser un point de Karma pour obtenir un bonus de +2 à un jet d'attaque au corps à corps.

[[talent_surprise_strike]]
=== Attaque surprise
*Prérequis :* <<ranks,Gardien>>, <<skill_stealth,Discrétion>> d10+

Une fois par combat, le personnage peut dépenser un point de Karma pour effectuer une _Attaque surprise_ (_Savage Worlds_ page 120), même si les circonstances ne devraient pas l'y autoriser.

[[talent_great_leap]]
=== Bondissement
*Prérequis :* <<ranks,Novice>>, Force d6+

Lors d'une course, le personnage peut ajouter un nombre de cases à son Allure égal à son <<ranks,Rang>> ×2.
Cette distance supplémentaire peut correspondre à un saut horizontal ou vertical.

[[talent_crushing_blow]]
=== Broyage
*Prérequis :* <<ranks,Gardien>>, Force d8+

Le personnage peut dépenser un point de Karma pour obtenir un bonus au jet de dégâts d'une attaque au corps à corps.
Le bonus aux dégâts obtenu est égal au <<ranks,Rang>> du personnage.

[[talent_chameleon]]
=== Caméléon
*Prérequis :* <<ranks,Gardien>>, <<skill_stealth,Discrétion>> d6+, <<skill_survival,Survie>> d8+

Le personnage peut dépenser un point de Karma pour obtenir un bonus à un jet de <<skill_stealth,Discrétion>> égal à son <<ranks,Rang>>.

[[talent_emotion_song]]
=== Chant d'émotion
*Prérequis :* <<ranks,Novice>>, Âme d6+

Le personnage peut dépenser un point de Karma après avoir donné une représentation d'une durée d'une demie heure minimum,
au cours de laquelle il peut utiliser la (ou les) forme(s) artistique(s) de son choix.
Cependant, le personnage doit définir l'objet de la représentation, ainsi que le sentiment qu'il désire faire naître envers celui-ci.

À l'issue de cette représentation, le personnage effectue un jet d'Âme.
Si ce jet est réussi, le personnage gagne un bonus égal à son <<ranks,Rang>> à tout jet d'interaction sociale.
Ce bonus n'est valable que contre un spectateur ayant été présent jusqu'à la fin de la représentation,
et pour un jet faisant entrer en jeu à la fois le sentiment et l'objet de la représentation.

[[talent_fearsome_charge]]
=== Charge terrifiante
*Prérequis :* <<ranks,Gardien>>, <<skill_riding,Équitation>> d6, <<skill_intimidation,Intimidation>> d6

Alors que sa monture effectue une action de Course en ligne droite, le personnage peut dépenser un point de Karma et une action pour faire un jet d'<<skill_intimidation,Intimidation>>.
Si le test d'<<skill_intimidation,Intimidation>> est un Succès, chaque adversaire présent la zone d'arrivée de la Course doit faire un test de Terreur (_Savage Worlds_ page 150).
La zone d'arrivée doit être de taille équivalente à un Grand Gabarit (_Savage Worlds_ page 110) au maximum.

[[talent_lionheart]]
=== Cœur de lion
*Prérequis :* <<ranks,Novice>>, Âme d6+

Le personnage bénéficie d'un bonus de +2 sur ses jets de terreur.

[[talent_maneuver]]
=== Dérobade
*Prérequis :* <<ranks,Novice>>, Intellect d6+

Le personnage peut dépenser un point de Karma et une action pour donner un malus à la Parade d'un adversaire.
Le malus est égal au <<ranks,Rang>> du personnage, et dure un round.

[[talent_enchanting]]
=== Enchantement
*Prérequis :* <<ranks,Gardien>>, <<edge_arcane_magic,Arcanes (Magie)>>

Le personnage peut enchanter des objets magiques.

Voir la section <<enchanting,Enchantement>> pour davantage de détails.

[[talent_temper_self]]
=== Endurcissement
*Prérequis :* <<ranks,Gardien>>, Âme d8+, Vigueur d8+

Le personnage peut dépenser un certain nombre de points de Karma après avoir effectué un rituel d'une demie-heure.
Cela lui permet de gagner un bonus d'Armure égal au nombre de point de Karma dépensés,
avec un maximum égal à son <<ranks,Rang>>.
Le bonus d'Armure dure un nombre d'heures égal au <<ranks,Rang>> du personnage.

[[talent_unshakeable_earth]]
=== Enracinement
*Prérequis :* <<ranks,Novice>>, Force d6+

Le personnage peut dépenser un point de Karma pour gagner un bonus de +2 pour éviter d'être mis à terre.
Ce bonus perdure alors jusqu'à ce qu'un de ses pieds quitte le sol.

[[talent_avoid_blow]]
=== Esquive
*Prérequis :* <<ranks,Compagnon>>, Agilité d8+

Le personnage peut dépenser un point de Karma pour bénéficier pour un round des effets suivants:

* un bonus de +1 à sa Parade ;
* un bonus de +1 à ses jet d'Agilité pour échapper aux effets d'une attaque de zone ;
* les ennemis qui le prennent pour cible ont un malus de -1 à leurs jets d'<<skill_ranged_weapons,Armes à distance>>.

[[talent_trap_initiative]]
=== Esquive des pièges
*Prérequis :* <<ranks,Compagnon>>, Agilité d6+, <<skill_notice,Perception>> d6+

Le personnage peut dépenser un point de Karma pour avoir le droit d'effectuer un jet d'Agilité juste avant de subir les effets d'un piège.
Si le jet est réussi, le personnage échappe totalement au piège.

[[talent_dead_fall]]
=== Fausse mort
*Prérequis :* <<ranks,Compagnon>>, Intellect d6+

Ce talent est une illusion.

Le personnage peut dépenser un point de Karma et une action pour simuler sa mort.
Tous les autres personnages présents se comportent comme s'il avait été mortellement touché.
Tant que l'état de Fausse mort dure, le personnage est À terre (_Savage Worlds_ page 118).
L'état dure jusqu'à ce que le personnage décide d'y mettre fin, ou qu'il se déplace.

Un personnage en état de Fausse mort peut effectuer n'importe quelle action.
Chaque action entreprise met cependant fin à l'illusion, sauf si le personnage entreprend une action supplémentaire et réussit un jet de <<skill_stealth,Discrétion>> pour chacune.

[[talent_false_sight]]
=== Faux semblants
*Prérequis :* <<ranks,Novice>>, Intellect d6+

Lorsqu'il lance un sort, le personnage peut choisir d'en faire un sort illusoire.
Un sort illusoire coûte 1 point de pouvoir de moins à lancer, mais ses cibles ont une chance d'en anuler complètement les effets.

Voir la section <<disbelief,Incrédulité>> pour davantage de détails.

[[talent_direction_arrow]]
=== Flèche de direction
*Prérequis :* <<ranks,Compagnon>>, <<skill_investigation,Renseignements>> d6+

Le personnage peut dépenser un point de karma pour bénéficier d'un bonus sur un jet de <<skill_investigation,Renseignements>>.
Ce bonus est égal à son <<ranks,Rang>>, mais n'est valable que si le personnage cherche à localiser un objet ou une personne dont il possède un élément matériel.

[[talent_flame_arrow]]
=== Flèche de feu
*Prérequis :* <<ranks,Compagnon>>, Âme d8+

Le personnage peut dépenser un point de Karma pour obtenir un bonus au jet de dégâts d'une attaque à distance.
Le bonus aux dégâts obtenu est égal au <<ranks,Rang>> du personnage.
Si l'arme utilisée est une arme de trait, la flèche tirée est détruite.

[[talent_forge_item]]
=== Forgeage
*Prérequis :* <<ranks,Novice>>, <<skill_repair,Forge>> d6+

Le personnage gagne le talent <<talent_enchanting,Enchantement>>, même s'il n'en satisfait pas les prérequis.
Il ne peut cependant s'en servir que pour créer des objets magiques majoritairement en métal (ou dans un autre matériau qu'il connaît via une <<skill_knowledge,Compétence artisanale et artistique>>).
Il peut utiliser sa Compétence <<skill_repair,Forge>> pour effectuer son <<enchanting,jet d'enchantement>>.

[[talent_mount_attack]]
=== Fureur animale
*Prérequis :* <<ranks,Gardien>>, <<skill_riding,Équitation>> d10+

La monture du personnage peut attaquer même si son cavalier a effectué une action ce round-ci (_Savage Worlds_ page 246).
La monture doit évidemment posséder un moyen de porter une attaque.

[[talent_speak_language]]
=== Glossolalie
*Prérequis :* <<ranks,Gardien>>, Intellect d6+

Après avoir entendu parler une langue pendant au minimum 1 minute, le personnage peut dépenser un point de Karma pour apprendre cette langue de manière permanente.

À la discrétion du MJ, un personnage qui apprend ce talent peut regagner un <<karma,point de Légende>> pour chaque <<skill_knowledge,Langue>> qu'il connait déjà.

[[talent_claw_shape]]
=== Griffes
*Prérequis :* <<ranks,Novice>>

Lorsqu'il effectue un jet d'<<skill_melee_weapons,Armes de mêlée>> à mains nues, le personnage est considéré comme armé.
De plus, il ajoute un bonus à ses jets de dégâts à mains nues égaux à son <<ranks,Rang>>.

[[talent_item_history]]
=== Histoire des objets
*Prérequis :* <<ranks,Compagnon>>, <<skill_notice,Perception>> d6+, <<skill_investigation,Renseignements>> d6+

Après avoir gardé auprès de lui un objet magique pendant une semaine, le personnage peut dépenser un point de Karma et effectuer un test d'Identification (un jet de <<skill_notice,Perception>>) de cet objet.
Le personnage apprend la nature d'une <<key_knowledge,connaissance clef>> de l'objet par succès et par Relance, à commencer par la <<key_knowledge,connaissance clef>> de Rang le plus faible.
Le personnage bénéficie d'un bonus de +1 à son test d'Identification par semaine supplémentaire pendant laquelle il conserve l'objet magique auprès de lui.

[[talent_summoning]]
=== Invocation
*Prérequis :* <<ranks,Compagnon>>, Âme d8+

Le personnage peut invoquer un type particulier d'esprits.
Le type d'esprits qu'il peut invoquer est indiqué lorsque le personnage achète ce talent.

Voir la section <<summoning,Invocation>> pour davantage de détails.

[[talent_durability]]
=== Longévité
*Prérequis :* <<ranks,Compagnon>>

Le personnage gagne un niveau de blessure supplémentaire.
Ce niveau impose un malus de blessure spécifique de -1.

Ce talent peut être acquis une fois par <<ranks,Rang>> au maximum.

Par exemple, un personnage ayant appris Longévité deux fois souffrira des malus de blessure suivants : -1 pour une, deux ou trois blessures encaissées, -2 à la quatrième blessure, et -3 à la cinquième blessure.
Ce personnage sera au minimum un Gardien de sa discipline.

[[talent_mount_durability]]
=== Longévité (monture)
*Prérequis :* <<ranks,Compagnon>>, <<skill_riding,Équitation>> d6+

Le personnage peut dépenser un point de Karma pour faire bénéficier à sa monture d'un bonus d'Armure égal à son <<ranks,Rang>>, pendant un nombre de rounds égal à son <<ranks,Rang>>.

De plus, la monture obtient le talent de Longévité.

[[talent_spell_matrix]]
=== Matrice de sorts
*Prérequis :* <<ranks,Novice>>, <<edge_arcane_magic,Arcanes (Magie)>>

Le personnage acquiert une matrice de sorts supplémentaire.
Ce talent peut être acheté plusieurs fois, mais un personnage ne peut posséder qu'un nombre maximum de matrices de sorts égal à son <<ranks,Rang>>.

Voir la section <<thread_magic,Magie des sorts>> pour davantage de détails.

[[talent_book_memory]]
=== Mémoire des livres
*Prérequis :* <<ranks,Gardien>>, Intellect d8+, <<skill_investigation,Renseignements>> d8+

Le personnage est considéré comme ayant toutes les <<skill_knowledge,Connaissances pures>> existantes.
Il doit pour cela avoir parcouru au moins une fois un livre renfermant l'information recherchée.

Si le personnage échoue malgré tout à un jet de <<skill_knowledge,Connaissance>>, il peut dépenser un point de Karma pour se rappeler l'information recherchée de manière fidèle.

[[talent_empathic_command]]
=== Ordre empathique
*Prérequis :* <<ranks,Novice>>, <<skill_riding,Équitation>> d6+

Si le personnage chevauche une monture ayant une attitude Serviable envers lui, cavalier et monture bénéficient des effets suivants :

* La monture réussit automatiquement son jet de Terreur si son cavalier le réussit.
  Si le jet de Terreur du cavalier est un échec, la monture fait son test normalement.
* Le cavalier ne souffre jamais du malus de plateforme instable.

[[talent_wood_skin]]
=== Peau de bois
*Prérequis :* <<ranks,Novice>>, Vigueur d6

Le personnage peut dépenser un point de Karma pour bénéficier d'un bonus à sa Résistance égal à son <<ranks,Rang>>, pendant un nombre de rounds égal à son <<ranks,Rang>>.

[[talent_animal_possession]]
=== Possession animale
*Prérequis :* <<ranks,Compagnon>>, Âme d6+

Le personnage peut dépenser un point de Karma pour posséder un animal ayant une attitude Amicale ou meilleure envers lui.
La possession a une durée maximale de <<ranks,Rang>> × 10 minutes.
Pendant tout le temps que dure la possession, le corps du personnage tombe en catatonie.

[[talent_spot_armor_flaw]]
=== Repérage du défaut de la cuirasse
*Prérequis :* <<ranks,Gardien>>, <<skill_notice,Perception>> d8+, <<skill_repair,Forge>> d8+

Le personnage peut dépenser un point de Karma et une action pour annuler un nombre de points d'Armure d'un adversaire au maximum égal à son <<ranks,Rang>>, pendant un round.

[[talent_bear_mark]]
=== Résistance à la marque
*Prérequis :* <<ranks,Novice>>

Une Horreur tentant de marquer le personnage souffre d'un malus égal au <<ranks,Rang>> du personnage.

* Si le jet de marquage est une réussite, le personnage souffre les effets habituels de la marque.
  Cependant, le personnage peut choisir de résister à une Horreur qui tente d'utiliser ses pouvoirs à travers cette marque.
  Pour cela, il dépense un point de Karma et effectue un jet d'Âme opposé à celle de l'Horreur.
  Si l'Horreur remporte le test opposé, elle peut utiliser son pouvoir normalement.
  Si c'est le personnage qui l'emporte, l'Horreur ne peut utiliser le pouvoir sur le personnage ... pour cette fois.
  Si une Relance est obtenue sur le jet d'Âme, la marque est « isolée » (voir point suivant).
* Si le jet de marquage est un échec, la marque est placée, mais est inoffensive pour le personnage.
  La marque est « isolée », et l'Horreur ne peut pas s'en servir contre le personnage.
  Le personnage, lui, peut dépenser un point de Karma pour savoir dans quelle direction et à quelle distance exactes se trouve l'Horreur la plus proche dont il a isolé la marque.

[[talent_fireblood]]
=== Sang de feu
*Prérequis :* <<ranks,Compagnon>>, Vigueur d6+

Le personnage peut dépenser un point de Karma pour effectuer un jet de guérison naturelle.
Dans le cadre de ce talent, ce jet ne lui prend qu'une action.
Ce jet ne bénéficie d'aucun bonus ou malus du aux conditions de convalescence.
Il souffre cependant des malus dus au blessures comme d'habitude.

[[talent_winning_smile]]
=== Sourire ravageur
*Prérequis :* <<ranks,Gardien>>, <<skill_persuasion,Persuasion>> d8+

Lors d'un jet de <<skill_persuasion,Persuasion>>, le personnage peut dépenser un point de Karma pour affecter un nombre d'Extras égal à son <<ranks,Rang>>.

[[talent_true_shot]]
=== Tir infaillible
*Prérequis :* <<ranks,Novice>>, <<skill_ranged_weapons,Armes à distance>> d6+

Le personnage peut dépenser un ou plusieurs points de Karma pour réduire les malus d'un jet d'<<skill_ranged_weapons,Armes à distance>>.
Chaque point de Karma ainsi dépensé réduit le malus qui s'applique au jet de 2 points.
Plusieurs points de Karma peuvent être dépensés de cette manière, avec un maximum d'un par <<ranks,Rang>>.

Ce talent est une exception à la règle qui ne permet d'utiliser au maximum qu'un seul <<karma,point de Karma>> pour un jet.

[[talent_multishot]]
=== Tir multiple
*Prérequis :* <<ranks,Gardien>>, <<skill_ranged_weapons,Armes à distance>> d10+

Le personnage peut dépenser un ou plusieurs points de Karma pour augmenter la CdT de son arme à distance.
La CdT de l'arme pour le round est égale au nombre de points de Karma dépensés +1.
Le personnage peut dépenser au maximum un point de Karma par <<ranks,Rang>> de cette manière.

[[talent_life_check]]
=== Ultime sursaut
*Prérequis :* <<ranks,Compagnon>>, Âme d8+, Vigueur d8+

Lorsque le personnage sombre dans un État critique (_Savage Worlds_ page 116), mais avant d'effectuer le jet de Vigueur correspondant, il peut dépenser un point de Karma pour effectuer un jet d'Âme.
Le malus de blessure ne s'applique pas à ce jet d'Âme.
Si ce jet est réussi, il sort de cet État critique, avec son nombre maximal de blessures.
Sur une relance, le personnage guérit en plus une de ses blessures.

[[talent_astral_sight]]
=== Vision astrale
*Prérequis :* <<ranks,Novice>>, <<skill_notice,Perception>> d6+

Le personnage peut dépenser un point de Karma pour percevoir l'espace astral durant un nombre de minutes égal à son type de dé de <<skill_notice,Perception>>.

[[talent_wind_catcher]]
=== Vol plané
*Prérequis :* <<ranks,Gardien>>, Âme d6+

Le personnage peut dépenser un point de Karma pour annuler les dégâts dus à une chute.
Cela fonctionne quelle que soit la distance de laquelle tombe le personnage.

Chaque round durant son vol plané, le personnage peut utiliser une action pour se déplacer horizontalement d'une distance maximale égale à la moitié de la distance chutée ce round-ci.





[[edges]]
== Atouts

[[edge_arcane_magic]]
=== Arcanes (Magie)
*Compétence :* <<skill_spellcasting,Incantation>> +
*Points de pouvoir :* Aucun +
*Pouvoirs :* 3 +

Les magiciens sont capables de lancer des sorts.

Voir la section <<thread_magic,Magie des sorts>> pour plus de détails.

[[edge_karma_affinity]]
=== Régénération de Karma
*Prérequis :* <<ranks,Compagnon>>, doit posséder une <<karma,Réserve de Karma>>.

Le personnage regagne un point de <<karma,Karma>> par jour, à son réveil.
Ce point gagné s'ajoute à celui qu'un adepte peut regagner chaque jour grâce à son rituel karmique.

[[edge_versatility]]
=== Polyvalence
*Prérequis :* <<ranks,Novice>>, <<race_humans,Humain>>

Le personnage peut apprendre n'importe quel <<talents,talent>>.
Le talent n'a pas besoin de figurer dans la liste de ses talents de <<disciplines,discipline>>.
Ceci mis à part, le personnage doit quand même satisfaire tous les prérequis du talent désiré.
Il doit aussi toujours trouver un instructeur possédant ce talent et acceptant de le lui enseigner.





[[thread_magic]]
== Magie des sorts

Un magicien n'a aucun point de Pouvoir, et il peut lancer autant de sorts qu'il le désire chaque jour.
Un sort se lance lorsque le magicien l'_incante_ en réussissant un jet d'<<skill_spellcasting,Incantation>>.
Ce jet souffre cependant d'un malus égal au nombre de points de Pouvoir requis par le sort.
Le magicien peut réduire ce malus grâce à une ou plusieurs actions de <<thread_weaving,tissage>> préalables à l'incantation.

[[spell_casting]]
1. Choix de la méthode de lancement de sorts :
** utilisation d'une <<matrix_casting,matrice de sorts>>
** lancement <<grimoire_casting,à travers un grimoire>>
** utilisation de la <<raw_magic,magie brute>>
2. Choix du sort à lancer et calcul du _malus d'incantation_.
   Ce malus est égal au nombre de points de Pouvoirs requis par le sort.
3. Réduction du _malus d'incantation_ grâce à un ou plusieurs <<thread_weaving,tests de tissage>>.
   Cette étape est facultative.
4. Incantation du sort : le magicien effectue un jet d'<<skill_spellcasting,Incantation>>.
** Si c'est une réussite, le sort fonctionne normalement.
** Si c'est un échec, rien ne se passe.

[[thread_weaving]]
=== Tissage de filaments
Le tissage de filaments de sorts est une action qui permet de réduire le _<<spell_casting,malus d'incantation>> d'un sort en cours de lancement.
Le magicien effectue un test de Tissage (un jet d'<<skill_spellcasting,Incantation>>, différent du jet de celui nécessaire pour le sort).
Chaque succès et Relance réduit le <<spell_casting,malus d'incantation>> de 2 points.

Le Tissage ne permet jamais d'obtenir des bonus au jet d'incantation.
Il ne permet pas non plus de réduire les malus autres que le _malus d'incantation_.

[[spell_matrix]]
=== Matrice de sorts

[[reattuning]]
==== Réharmonisation
Une Matrice de sorts peut contenir un seul sort à la fois.
Tout magicien peut à tout moment _réharmoniser_ ses matrices en méditant 10 minutes.
Cela lui permet de redéfinir quel sort est contenu dans quelle matrice.

S'il n'a pas le temps d'attendre ces 10 minutes, il peut choisir de _réharmoniser à la va-vite_.
Le magicien dépense une action et effectue un jet d'<<skill_spellcasting,Incantation>>.
Chaque réussite et Relance lui permet de placer un nouveau sort dans une de ses matrices.
Un échec « vide » toutes ses matrices de sorts.

[[matrix_casting]]
==== Lancement de sorts
Le magicien doit <<learn_spell,connaître personnellement>> le sort à lancer.

Lancer un sort contenu dans une matrice se fait selon la <<spell_casting,procédure normale>>.

*Contrecoup :*
Hormis échouer à lancer son sort, le magicien ne peut souffrir d'aucun effet indésirable supplémentaire, quel que soit le résultat de son dé d'<<skill_spellcasting,Incantation>>.

[[grimoire]]
=== Grimoires

[[learn_spell]]
==== Apprendre un nouveau sort
Apprendre un sort est une action qui coûte un <<karma,point de karma>> mais ne requiert aucun test.
Un personnage peut apprendre de la sorte un sort d'un <<ranks,cercle>> supérieur au sien, mais il lui en coûte un <<karma,point de karma>> supplémentaire par <<ranks,cercle>> manquant.

[[grimoire_casting]]
==== Lancement de sorts à travers un grimoire
Un magicien peut lancer un sort à travers un grimoire, que ce grimoire soit le sien ou appartienne à quelqu'un d'autre.
Il n'a pas besoin de <<learn_spell,connaître personnellement>> le sort à lancer, mais celui-ci doit figurer dans le grimoire.

Lancer un sort à travers un grimoire se fait selon la <<spell_casting,procédure normale>>, mais le malus d'incantation est augmenté de 2.

Un personnage peut lancer un sort d'un <<ranks,cercle>> supérieur au sien, cependant, son <<spell_casting,Test d'Incantation>> ainsi que son <<thread_weaving,Test de Tissage>> souffrent dans ce cas d'un malus de -1 par <<ranks,Cercle>> manquant.

*Contrecoup :*
Si le magicien obtient un 1 sur son dé d'<<skill_spellcating,Incantation>> (peu importe le dé Joker), il est automatiquement Secoué.
S'il était déjà Secoué, il subit une blessure.
Le sort qu'il tentait de lancer est effacé du grimoire de manière permanente.

[[raw_magic]]
=== Magie brute
Le magicien doit <<learn_spell,connaître personnellement>> le sort à lancer.
Cependant, le sort n'a pas besoin d'être actuellement contenu dans une de ses matrices.

Lancer un sort contenu dans une matrice se fait selon la <<spell_casting,procédure normale>>.

*Contrecoup :*
Immédiatement après avoir utilisé la magie brute pour lancer un sort, un personnage a toujours une probabilité de subir un contrecoup,
quel que soit le résultat du lancement du sort ou de son dé d'<<skill_spellcasting,Incantation>>.

Pour connaître le détail du contrecoup, il faut effectuer un test de Distorsion.
Le dé à lançer dépend de la nature de l'espace astral à l'endroit où se trouve le personnage, comme indiqué sur la <<warping,table de Magie brute>>.

[[warping]]
.Magie brute
[width=40%, options="header"]
|===
|Région    |Type |Dégâts

|Saine     |d4   |1d6
|Dégagée   |d6   |2d6
|Souillée  |d8   |3d6
|Corrompue |d10  |4d6
|===

Le test de Distorsion bénéficie d'un bonus égal au <<ranks,Rang>> du sort lancé.

* Si le test est un échec, rien ne se passe.
* Si le test est réussi, le personnage subit des dégâts, comme indiqué sur la <<warping,table de Magie brute>>.
* Si test obtient une Relance, le personnage est en outre marqué par l'Horreur la plus proche.


[[disbelief]]
=== Incrédulité

Certains sorts sont illusoires : leurs effets sont réels uniquement si leur cible y croit.
Lorsqu'il est la cible d'un sort, que celui-ci soit réellement illusoire ou non, la cible peut tenter de percer à jour une éventuelle illusion.
Elle effectue un jet d'incrédulité, qui consiste en un jet de <<skill_notice,Perception>>, d'Intellect ou d'Âme, au choix du personnage.
Cela constitue une action.

* Si le jet est réussi et que le sort est illusoire, celui-ci n'a aucun effet.
  Avec une Relance, le personnage incrédule peut éventuellement entreprendre ses autres actions du round sans que celles-ci souffrent du malus d'actions multiples (_Savage Worlds_ page 112).
* Si le jet échoue, le personnage subit pleinement les effets du sort illusoire.
* Si le sort auquel le personnage résiste n'est pas une illusion, le personnage en subit pleinement les effets, que le jet d'incrédulité soit un succès ou non.





[[spell_list]]
== Grimoire

* Le « rang » d'un personnage au sens Earthdawn correspond à son <<ranks,Cercle>>.
* Si un sort est indiqué « MOOT », c'est que ses effets peuvent être improvisés sans difficultés.
  La plupart du temps, les détails chiffrés ne sont pas importants.

[[elementalist_spells]]
=== Sorts d'élémentaliste

==== Sorts du premier cercle
*Arme de Feu*: <<spell_smite,Frappe>> +
*Camouflage*: <<spell_boost_lower_trait,Augmentation de Trait>> (<<skill_stealth,Discrétion>>) +
*Langage des plantes*: <<spell_speak_language,Compréhension des langues>> (plantes uniquement) +
*Monte-en-l'Air*: <<spell_boost_lower_trait,Augmentation de Trait>> (<<skill_climbing,Escalade>>) +
*Poussière de Cristal*: <<spell_bolt,Éclair>> (cible unique) +
*Purification de l'eau*: MOOT +
*Réchauffage des Aliments*: MOOT +
*Résistance au Feu*: <<spell_armor,Armure>> (vs feu uniquement) +
*Résistance au Froid*: <<spell_armor,Armure>> (vs froid uniquement) +

==== Sorts du second cercle
*Branchies*: <<spell_environmental_protection,Adaptation environnementale>> (respiration sous l'eau) +
*Collage*: <<spell_entangle,Enchevêtrement>> (couple de cibles) +
*Ébullition*: MOOT +
*Lance de glace*: Poussière de Cristal en moins bon +
*Ralentissement du métal*: <<spell_deflection,Déflexion>> (arme unique en métal) +
*Retour au bercail*: MOOT +
*Stérilisation*: MOOT +
*Tapis de glace*: <<spell_pummel,Déluge de coups>> (100m², coté max 20m, cibles: Agilité => à terre, pas repoussées, pas secouées) +

==== Sorts du troisième cercle
*Création d'Esprit Porteur*: <<spell_summon_ally,Convocation d'allié>> (Force et Vigueur=Incantation, d4-2 partout, n'attaque pas) +
*Faux fond*: <<spell_entangle,Enchevêtrement>> (à lancer sur une mare) +
*Festin végétal*: MOOT +
*Fléau de glace*: <<spell_bolt,Éclair>> +
*Œil dans le dos*: MOOT +
*Réparation*: <<skill_repair,Réparation>> instantanée = <<skill_spellcasting,Incantation>> +
*Treillage Céleste*: MOOT (+2 aux jets d'<<skill_climbing,Escalade>> pour y grimper) +
*Trône des vents*: <<spell_speed,Vitesse>> +

==== Sorts du quatrième cercle
*Allègement*: MOOT +
*Bouclier d'Énergie*: <<spell_damage_field,Zone de dégâts>> (uniquement contre adversaires qui réussissent leur attaque sans Relance) +
*Bourrasque*: <<spell_pummel,Déluge de coups>> +
*Ébranlement du sol*: <<spell_entangle,Enchevêtrement>> (rayon:25m, pas de malus Force) +
*Pâte suffocante*: <<spell_blind,Aveuglement>> +
*Rappel des armes*: MOOT +
*Sphère de Blizzard*: <<spell_blast,Explosion>> +

==== Sorts du cinquième cercle
*Ailes de Métal*: <<spell_fly,Vol>> +
*Boule de Feu*: <<spell_blast,Explosion>> +
*Cage de Pierre*: Âme pour dissiper, Résistance 8, vole en éclats à la première blessure +
*Hurlements Métalliques*: <<spell_fear,Terreur>> (cibles doivent porter du métal) +
*Tige de Terre*: bâton, Force+d8 (Force+d10 si Relance) +



[[illusionist_spells]]
=== Sorts d'illusionniste

Les sorts marqués d'une astérisque (*) sont des <<disbelief,illusions>>.

==== Sorts du premier cercle

*Bonne Figure* +*+: <<spell_boost_lower_trait,Augmentation de Trait>> (<<skill_stealth,Persuasion>>, uniquement pour convaincre de son identité ou se comporter en fonction de son rôle) +
*Bourse Plate*: MOOT +
*Contact Rassurant*: La cible acquiert l'<<eges,Atout>> Brave. +
*Corde Enchantée*: MOOT +
*Décalage visuel* +*+: MOOT +
*Déguisement du Métal* +*+: MOOT +
*Lumière*: <<spell_light_obscure,Lumière>> ou <<spell_blind,Aveuglement>> (malus de -2 au test d'<<skill_spellcasting>>). +
*Voix Invisibles* +*+: MOOT +

==== Sorts du second cercle
*Activité Innocente* +*+: MOOT +
*Éclair vert* +*+: <<spell_bolt,Éclair>> +
*Habillage* +*+: <<spell_boost_lower_trait,Augmentation de Trait>> (<<skill_stealth,Persuasion>>, pour améliorer l'attitude) +
*Idée fixe* +*+: MOOT +
*Manteau de pluie*: <<spell_environmental_protection,Adaptation environnementale>> (froid chaud) et <<spell_armor,Armure>> (contre dégâts de pluie naturelle ou magique uniquement) +
*Manteau monstrueux* +*+: <<spell_smite,Frappe>> +
*Véritable Éclair vert*: <<spell_bolt,Éclair>> +

==== Sorts du troisième cercle
*Affaiblissement Karmique* +*+: MOOT (utiliser un <<karma,point de Karma>> ne rajoute que ++1 au lieu de +2+) +
*Alarme* +*+: MOOT +
*Faux piège* +*+: MOOT +
*Serrure Impossible* +*+: MOOT (-2 au test de <<skill_lockpicking,Crochetage>> +
*Sphère de Non-Présence* +*+: <<spell_invisibility,Invisibilité>> (sphère inamovible uniquement ; toute personne y pénétrant a droit à un <<disbelief,test d'Incrédulité>>) +
*Suffocation* +*+: <<spell_bolt,Éclair>> (cible unique, plus de PP pour -1 à tous ses tests). +
*Trou de Mémoire* +*+: <<spell_confusion,Confusion>> +

==== Sorts du quatrième cercle
*Alarme Améliorée* +*+: Comme *Alarme*, mais dure plus longtemps. +
*Appel du Devoir* +*+: <<spell_puppet,Marionnette>> (un seul ordre, petit gabarit) +
*Aveuglement* +*+: <<spell_blind,Aveuglement>> +
*Cercle de Bien-Être*: MOOT (++2+ aux tests de récupération effectués au sein du cercle) +
*Immobilisation* +*+: <<spell_puppet,Marionnette>> (immobilisation uniquement) +
*Multi-Missile* +*+: <<spell_smite,Frappe>> (armes à distance uniquement) +


==== Sorts du cinquième cercle
*Amélioration du Karma* +*+: MOOT (utiliser un <<karma,point de Karma>> rajoute ++3 au lieu de +2+) +
*Belles Manières* +*+: <<spell_boost_lower_trait,Augmentation de Trait>> (<<skill_stealth,Persuasion>>, tant que le personnage se comporte en gars de la Haute) +
*Douce Rêverie* +*+: <<spell_slumber,Sommeil>> +
*Muraille de Feu* +*+: <<spell_barrier,Barrière>> de feu +
*Tapis volant*: <<spell_fly,Vol>> (à lancer sur un tapis) +



[[nethermancer_spells]]
=== Sorts de nécromancien

==== Sorts du premier cercle
TODO

==== Sorts du second cercle
TODO

==== Sorts du troisième cercle
TODO

==== Sorts du quatrième cercle
TODO

==== Sorts du cinquième cercle
TODO



[[wizard_spells]]
=== Sorts de sorcier

==== Sorts du premier cercle
TODO

==== Sorts du second cercle
TODO

==== Sorts du troisième cercle
TODO

==== Sorts du quatrième cercle
TODO

==== Sorts du cinquième cercle
TODO





[[summoning]]
== Invocation

Le personnage peut invoquer un esprit en effectuant un test d'<<skill_summoning,Invocation>>.

* En cas de réussite, l'esprit est invoqué.
  L'esprit doit au personnage un service, plus un par Relance obtenue.
* En cas d'échec, le personnage est Sonné.
* Si le personnage obtient un 1 sur son dé d'<<skill_summoning,Invocation>> (peu importe le dé Joker), l'esprit est invoqué hors de son contrôle.

Le rituel d'invocation prend une minute est est assorti des modificateurs suivants :

[[summoning_modifiers]]
.Invocation: modificateurs
[options="header"]
|===
|Description                                        |Modificateur

|Puissance de l'esprit                              |-Puissance
|L'invocateur connaît le nom de l'esprit            |+2
|Lieu de l'invocation favorable pour l'esprit ^1^   |+2
|Le rituel d'invocation dure une heure ou plus      |+2
|L'invocateur désire un pouvoir particulier         |-2
|Lieu de l'invocation défavorable pour l'esprit ^1^ |-2
|Le rituel d'invocation ne dure qu'un round         |-2
|===
^1^ Voir la <<spirits,description>> de chaque esprit.

[[spirits]]
=== Esprits

La caractéristique principale d'un esprit est sa Puissance, exprimé comme un dé dont la valeur peut aller de d4-2 à d12.
Les esprits dont la Puissance est supérieure à d12 existent, mais ne sont pas invocables par la méthode d'<<skill_summoning,invocation>> habituelle.

Tous les traits d'un esprit sont égaux à sa Puissance.
Les esprits possèdent uniquement les compétences <<skill_melee_weapons,Armes de mêlée>> et <<skill_notice,Perception>>, à un indice égal à leur Puissance.

À noter qu'une région Souillée ou Corrompue compte automatiquement comme un environnement défavorable pour un esprit.

==== Élémentaire d'air

*Matériau d'invocation :* Vent fort +
*Environnement favorable :* Tempête ou haute altitude +
*Environnement défavorable :* Intérieurs

==== Élémentaire d'eau

*Matériau d'invocation :* Rivière, mare +
*Environnement favorable :* Lacs, mers +
*Environnement défavorable :* Sur terre ou dans les airs

==== Élémentaire de bois

*Matériau d'invocation :* Arbre ou meuble en bois +
*Environnement favorable :* Forêt ou jungle +
*Environnement défavorable :* Incendie, intérieurs, dans les airs, sur l'eau, sous terre

==== Élémentaire de feu

*Matériau d'invocation :* Grand feu de camp +
*Environnement favorable :* Incendie ou coulée de lave +
*Environnement défavorable :* Rivière ou mers

==== Élémentaire de terre

*Matériau d'invocation :* Terre meuble, rochers +
*Environnement favorable :* Hautes montagnes ou sous terre +
*Environnement défavorable :* Sur l'eau ou dans les airs

==== Esprit des morts

*Matériau d'invocation :* Miroir ou encens +
*Environnement favorable :* Cimetière, charnier, meurtre récent, champ de bataille +
*Environnement défavorable :* Terre consacrée

==== Squelette

*Matériau d'invocation :* Ossements +
*Environnement favorable :* Cimetière ou charnier +
*Environnement défavorable :* Terre consacrée

==== Zombie

*Matériau d'invocation :* Cadavre (relativement) intact +
*Environnement favorable :* Cimetière ou charnier +
*Environnement défavorable :* Terre consacrée





[[magic_items]]
== Objets magiques

Il ne faut pas confondre les objets magiques, aussi appelés objets à filaments, et utilisés par les seuls adeptes,
avec les objets enchantés (allume-feux, bottes sèches, manteaux chauffants, ...), d'un usage beaucoup plus usuel.
Pour plus de détails sur les objets enchantés, se reporter aux tables d'équipement.

Pour utiliser les pouvoirs d'un objet magique, un adepte doit se lier à lui en lui attachant un filament.
Un tel filament possède un Rang, et permet d'utiliser les pouvoirs de l'objet d'un Rang égal ou inférieur.
Un adepte ne peut pas tisser un filament d'un Rang supérieur au <<ranks,sien>>.
Un adepte peut maintenir en même temps un nombre maximal de filaments égal à son <<ranks,Rang>>.
Attacher un filament à un objet magique (ou augmenter le Rang d'un filament existant) est une action qui coûte un <<karma,point de karma>> mais ne requiert aucun test ; l'adepte doit cependant connaître toutes les <<key_knowledge,Connaissances clefs>> de l'objet de Rang inférieur ou égal au Rang du filament désiré.

Un adepte peut à tout moment détruire un filament qu'il a lui-même attaché à un objet magique.
Il ne pourra cependant pas ré-attacher ce filament avant que 24 heures se soient écoulées.

[[key_knowledge]]
=== Connaissances clefs

Chaque Rang d'un objet magique est lié à une _Connaissance clef_.
Un personnage désirant attacher un filament à l'objet magique doit connaître cette Connaissance clef.
Pour apprendre la _nature_ de la Connaissance clef à connaître, le personnage doit utiliser le talent <<talent_item_history,Histoire des objets>>, ou faire appel aux services de quelqu'un d'autre qui maîtrise ce talent.
Une fois qu'il a appris la nature de la Connaissance clef nécessaire (par exemple : « le nom du créateur de l'objet », « sa composition exacte », ou encore « la manière dont est mort son dernier possesseur »), le personnage doit effectuer des recherches pour apprendre la Connaissance clef elle-même (en reprenant les exemples précédents : « St. Fu le Muet », « 80% d'acier, 15% de terre élémentaire, et 5% d'orichalque », ou encore « il y a 400 ans, étouffé par son édredon »).
Ces recherches peuvent aller du simple usage de la Compétence <<skill_investigation,Renseignements>> jusqu'à mener à son terme une quête épique à l'autre bout du monde.

[[enchanting]]
=== Enchantement

Il est possible de transformer un objet ordinaire en objet à filaments (ou d'améliorer un objet à filaments existant) de deux manières différentes.

* Tout d'abord, le personnage peut utiliser l'alchimie.
  Il s'agit d'un processus long et complexe, mais maîtrisé et aux résultats relativement garantis. +
  C'est la méthode favorite des armuriers pour forger des armes et armures magiques.
  Les élémentalistes aussi utilisent cette technique lorsqu'il tissent des noyaux de matières élémentaires dans un objet existant.
  Enfin, les nécromanciens utilisent cette méthode pour forcer un esprit à posséder un objet. +
  Dans ce cas, le test d'Alchimie est un jet d'Intelligence, et a une durée d'un mois.
* La seconde méthode est plus instinctive, et offre des résultats variables.
  Elle consiste à rendre un objet magique, de manière volontaire ou non, suite à l'accomplissement d'un fait particulièrement héroïque.
  L'objet magique à créer doit avoir été indispensable à la réalisation du Haut Fait par le personnage. +
  Dans ce cas, le test d'Alchimie est un jet d'Âme, et est instantané.

[[enchanting_modifiers]]
.Enchantement: modificateurs
[options="header"]
|===
|Description                                        |Modificateur

|Puissance de l'objet à enchanter                   |-2×Rang
|L'objet a été indispensable à un Haut Fait ou plus |+1 à +4
|L'objet inclut des matériaux élémentaires ou rares |+1 à +2
|L'objet a été fabriqué par l'enchanteur lui-même   |+1
|L'objet est un objet de trame                      |+Rang
|Le rituel d'enchantement est particulièrement long |+1
|===

[[magic_item_creation]]
=== Création

Chaque objet magique peut accorder un ou plusieurs pouvoirs dont les effets correspondent à un nombre de <<build_your_legend,points de Légende>> égal au <<ranks,Rang>> de l'objet.
La puissance des pouvoirs que peut accorder un objet à filaments est limitée par le <<magic_items,Rang du filament>> qui lui est attaché ; le Rang maximal du filament est lui-même limité par le Rang de l'objet.

.Objets magiques
[options="header"]
|===
|Pouvoir                                      |Coût

|Doubler la portée ^1^                        |1
|Augmenter le dé de dégâts de 1 ^2^           |1
|Augmenter l'armure de 1 ^3^                  |1

|Augmenter un Attribut de 1                   |2
|Augmenter une <<skills,Compétence>> de 1 ^4^ |1
|Nouvelle <<skill_knowledge,Connaissance>>    |1
|Nouvel <<edges,Atout>> ^5^                   |2
|===
^1^ Armes à distance uniquement. +
^2^ Armes uniquement. Le bonus de dégâts n'est pas limité par la Force de l'utilisateur. +
^3^ Armure uniquement. Le bonus d'armure s'applique aussi contre les dégâts magiques. +
^4^ Si le porteur ne possède pas la Compétence, il l'acquiert à d4. +
^5^ Le porteur n'a pas besoin d'en satisfaire les prérequis.





[[design_notes]]
== Annexe 1: Notes de conception

L'univers d'Earthdawn est fantastique, mais son système de jeu est lourd et difficile d'accès.
Savage Worlds est un système plus léger, connu de mes joueurs, dont j'ai le livre de base en français,
et qui conserve la saveur de pouvoir lancer chaque dé différent, du d4 au d20, au cours d'une partie.

Conserver la « saveur » d'un jeu passe par en reprendre les termes.
D'autant plus que le système d'_Earthdawn_ est intimement lié à son background.
On y parle de cercles de disciplines, de rangs de talents, de trames et de filaments, de points de Légende, et ainsi de suite.
J'ai désiré reprendre un maximum de ces termes, sans trop en faire non plus : il faut que ça reste du _Savage Worlds_.

Il faut conserver le système de jeu rapide (surtout durant les combats) et flexible (pour ne pas limiter les builds de persos).

Chaque discipline doit conserver ses talents et capacités emblématiques, mais pas tout non plus.
Il y a quand même un max de trucs qui ne servent à rien, ou sont juste ... bof.

Virer les points de Pouvoir pour les magiciens ; la limitation doit venir des matrices de sorts et du temps parfois long pour tisser des effets puissants.
Comme dans tous les jdr, éviter le syndrôme du magot qui roxe tout et fait tout même le café pendant que les autres PJ en sont réduits à commenter le combat en coulisse.
Éviter les pièges habituels : les esprits ne doivent pas être plus puissants que les PJs et faire le boulot à leur place, incanter depuis un grimoire ça peut être pratique mais c'est lourdingue, la magie brute ça fait peur, une Horreur c'est mystérieux, puissant ET ça fait peur.

Garder les objets magiques funs, avec un background et une mécanique moteurs de scénarios.
Mais les gros roxxeurs doivent rester les adeptes : un om est un plus, mais un adepte doit pouvoir faire sans.

Sublimer l'approche pulp de _Savage Worlds_, et lui rajouter l'épique d'_Earthdawn_ !

[[sw_spells]]
== Annexe 2: Sorts de Savage Worlds

[[spell_environmental_protection]] N *Adaptation environnementale* (_Savage Worlds_ page 193) +
[[spell_wall_walker]] N *Adhérence* (_Savage Worlds_ page 193) pattes d'araignée auto +
[[spell_beast_friend]] N *Ami des bêtes* (_Savage Worlds_ page 193) commande animaux +
[[spell_armor]] N *Armure* (_Savage Worlds_ page 194) +
[[spell_boost_lower_trait]] N *Augmentation / Diminution de trait* (_Savage Worlds_ page 194) +
[[spell_blind]] N *Aveuglement* (_Savage Worlds_ page 194) cible(s): Agilité à -2 => -2(-4) Parade +
[[spell_banish]] V *Banissement* (_Savage Worlds_ page 194) Incantation vs Âme +
[[spell_barrier]] A *Barrière* (_Savage Worlds_ page 195) solide +
[[spell_Stun]] N *Choc* (_Savage Worlds_ page 195) cibles g.moyen: Vigueur => Secouées +
[[spell_speak_language]] N *Compréhension des langues* (_Savage Worlds_ page 195) +
[[spell_confusion]] N *Confusion* (_Savage Worlds_ page 195) cible: Intellect à -2 => Secouée +
[[spell_summon_ally]] N *Convocation d'allié* (_Savage Worlds_ page 196) gardien, sentinelle, clone ou autre +
[[spell_growth_shrink]] A *Croissance* / *Rapetissement* (_Savage Worlds_ page 197) change Taille +
[[spell_deflection]] N *Déflexion* (_Savage Worlds_ page 197) attaquants: -2(-4) au Combat, Tir +
[[spell_disguise]] A *Déguisement* (_Savage Worlds_ page 198) alter self +
[[spell_pummel]] A *Déluge de coups* (_Savage Worlds_ page 198) cibles cône: Force => 2d6m + à terre ou Secouée si contre mur +
[[spell_detect_conceal_arcana]] N *Détection* / *Dissimulation d'Arcanes* (_Savage Worlds_ page 198) +
[[spell_dispel]] A *Dissipation* (_Savage Worlds_ page 198) +
[[spell_divination]] H *Divination* (_Savage Worlds_ page 199) +
[[spell_warrior_s_gift]] A *Don du guerrier* (_Savage Worlds_ page 199) cible gagne un Atout au choix +
[[spell_bolt]] N *Éclair* (_Savage Worlds_ page 200) ATK projectile(s) +
[[spell_entangle]] N *Enchevêtrement* (_Savage Worlds_ page 200) cible: Agilité => -2 Allure, skills Force ou Agilité +
[[spell_burrow]] N *Enfouissement* (_Savage Worlds_ page 201) +
[[spell_blast]] A *Explosion* (_Savage Worlds_ page 201) ATK de zone +
[[spell_smite]] N *Frappe* (_Savage Worlds_ page 201) +2(+4) aux dégâts d'une arme +
[[spell_greater_healing]] V *Grande guérison* (_Savage Worlds_ page 201) +
[[spell_healing]] N *Guérison* (_Savage Worlds_ page 202) +
[[spell_intangibility]] H *Intangibilité* (_Savage Worlds_ page 202) +
[[spell_invisibility]] A *Invisibilité* (_Savage Worlds_ page 202) +
[[spell_mind_reading]] N *Lecture des pensées* (_Savage Worlds_ page 203) +
[[spell_light_obscure]] N *Lumière* / *Ténèbres* (_Savage Worlds_ page 203) annule ou donne -6 d'obscurité +
[[spell_elemental_manipulation]] N *Manipulation élémentaire* (_Savage Worlds_ page 203) petits effets +
[[spell_puppet]] V *Marionnette* (_Savage Worlds_ page 204) cible: Âme => control +
[[spell_burst]] N *Rafale* (_Savage Worlds_ page 204) ATK cône +
[[spell_slow]] A *Ralentissement* (_Savage Worlds_ page 205) cible: Âme => mvt=action -> malus AMultiples +
[[spell_quickness]] A *Rapidité* (_Savage Worlds_ page 205) deux rounds d'action +
[[spell_havoc]] A *Ravage* (_Savage Worlds_ page 205) genre tornade +
[[spell_succor]] N *Secours* (_Savage Worlds_ page 206) soigne niveaux de fatigue +
[[spell_drain_power_points]] H *Siphon d'énergie* (_Savage Worlds_ page 206) récup PP +
[[spell_slumber]] A *Sommeil* (_Savage Worlds_ page 206) cibles gab moyen: Âme => dodo +
[[spell_telekinesis]] A *Télékinésie* (_Savage Worlds_ page 206) +
[[spell_teleport]] A *Téléportation* (_Savage Worlds_ page 207) genre 20-30m +
[[spell_fear]] N *Terreur* (_Savage Worlds_ page 208) cibles grand gab Terreur => jet sur table +
[[spell_shape_change]] N *Transformation* (_Savage Worlds_ page 208) métamorphose animale +
[[spell_darksight]] N *Vision dans le noir* (_Savage Worlds_ page 209) réduit(ignore) malus d'obs +
[[spell_farsight]] A *Vision lointaine* (_Savage Worlds_ page 209) réduit malus de distance +
[[spell_speed]] N *Vitesse* (_Savage Worlds_ page 209) booste l'Allure +
[[spell_fly]] V *Vol* (_Savage Worlds_ page 209) +
[[spell_zombie]] V *Zombi* (_Savage Worlds_ page 209) +
[[spell_damage_field]] A *Zone de dégâts* (_Savage Worlds_ page 210) cible et/ou adversaires: atk réussie => 2d6(2d8) dégâts
