= Savage Dawns
:toc: left
:toc-title: Table des matières
:toclevels: 2



== Progression du personnage

Tous les 5 XP, un personnage gagne un Cercle.
Il bénéficie alors d'une Progression (_Savage Worlds_ page 170).

[[ranks]]
.Tableau des rangs
[width=40%, options="header"]
|===
|XP    |Cercle |Rang       |Équivalent

| 0-19 | 1-4   |Novice     |Novice
|20-39 | 5-8   |Compagnon  |Aguerri
|40-59 | 9-12  |Gardien    |Vétéran
|60-79 |13-16  |Maître     |Héroïque
| 80+  | 17+   |Légende    |Légendaire
|===

Pour qu'un adepte puisse passer au Rang supérieur, il lui est nécessaire de trouver un instructeur plus avancé dans sa discipline et qui accepte de l'entraîner.
Cela n'est en général pas nécessaire pour un passage de Cercle.

Un adepte d'un Rang au moins égal à celui de Compagnon peut invoquer un maître fantôme.
Chaque rituel du maître fantôme a une durée d'une nuit.



== Compétences

Combat (Agilité)
Conduite (Agilité)
Connaissance(~) (Intellect)
Crochetage (Agilité)
Discrétion (Agilité)
Équitation (Agilité)
Escalade (Force)
Intimidation (Âme)
Jeu (Intellect)
Lancer (Agilité)
Natation (Agilité)
Navigation (Agilité)
Perception (Intellect)
Persuasion (Âme)
Pilotage (Agilité)
Pistage (Intellect)
Recherche (Intellect)
Réparation (Intellect)
Réseaux (Intellect)
Sarcasme (Intellect)
Soins (Intellect)
Survie (Intellect)
Tir (Agilité)

[[option_skills_made_easy]]
[NOTE.option,caption="Règle optionnelle"]
====
*Compétences facilitées*

Augmenter une Compétence dont la valeur est supérieure ou égale au Trait associé
ou prendre une nouvelle Compétence à d4 se fait au même prix
qu'augmenter une compétence dont la valeur est inférieure au Trait associé.

Cette règle est valable lors de la création de personnage
tout comme lors de sa progression.

Cela signifie qu'à la création de personnage, chaque dé de Compétence coûte un point,
quel que soit le dé et quelle que soit la valeur du trait associé.

Lorsque le personnage bénéficie d'une Progression, celle-ci permet au personnage d'augmenter deux Compétences,
et ce, quelle que soit leur nouvelle valeur et quelle que soit la valeur du trait associé.
====

[[option_knowledges]]
[NOTE.option,caption="Règle optionnelle"]
====
*Expertises*

La Compétence « Connaissance » disparaît.
À la place, chaque personnage peut acquérir différentes Expertises.
Chaque Expertise s'aquiert au prix d'un dé de Compétence, que ce soit à la création de personnage ou lors d'une Progression.
Une Expertise n'a pas de dé associé : soit un personnage la possède, soit il ne la possède pas.

Une Expertise permet au personnage qui la possède de tenter une action
qui sort de l'usage habituel d'une Compétence ou d'un Trait donnés.

Par exemple, une Expertise « Histoire » ou « Loi » permettra de tenter des tests de Culture générale ayant trait à ces sujets ;
le test d'Intellect associé ne subira alors aucun malus.
====



[[karma]]
== Karma

Un adepte ne gagne aucun Jeton au début d'une session de jeu.
À la place, il gagne un nombre de points de Karma égal à la taille de sa réserve de Karma.
La taille de la réserve de Karma d'un adepte est égale à son <<ranks,Cercle>>.

Un point de Karma peuvent être dépensé pour :

* Obtenir un bénéfice identique à celui d'un Jeton (_Savage Worlds_ page 106).
* Obtenir un bonus de +2 à certains jets, dépendant de la <<disciplines,discipline>> du personnage.
  Pour un jet donné, un maximum d'un seul point de Karma peut être utilisé de cette manière.

Une seule fois par jour, un adepte peut effectuer un rituel karmique propre à sa discipline.
Ce rituel lui permet de regagner un point de Karma.

[[disciplines]]
== Disciplines

Chaque discipline est un Atout professionel (_Savage Worlds_ page 63).
Ces atouts sont accessibles dès la création d'un personnage, ou bien plus tard, grâce à une Progression.

À la discrétion du MJ, un adepte peut posséder plusieurs disciplines, jusqu'à une limite d'une par Rang.
Quel que soit le nombre de disciplines qu'il possède, cela n'accroit pas la taille de sa <<karma,réserve de Karma>>.



[[discipline_archer]]
=== Archer

*Prérequis :* <<ranks,Novice>>, Tir d8+

Un Archer acquiert l'atout Vigilance.

Un Archer peut utiliser un point de Karma dans le cadre d'un jet de Tir.

*Talents de discipline :* <<talent_flame_arrow,Flèche de feu>>, <<talent_true_shot,Tir infaillible>>, <<talent_multishot,Tir multiple>>.



[[discipline_weaponsmith]]
=== Armurier

*Prérequis :* <<ranks,Novice>>, Âme d6+, Réparation d6+

Le Charisme d'un Armurier est augmenté de 2.
Il ne doit cependant jamais mentir, et toujours tenir sa parole, sous peine de perdre ce bénéfice.

Un Armurier peut utiliser un point de Karma dans le cadre d'un jet de Réparation ou de Recherche.

*Talents de discipline :* <<talent_temper_self,Endurcissement>>, <<talent_forge_item,Forgeage>>, <<talent_item_history,Histoire des objets>>



[[discipline_cavalryman]]
=== Cavalier

*Prérequis :* <<ranks,Novice>>, TODO

TODO

Un Cavalier peut utiliser un point de Karma dans le cadre d'un jet d'Équitation, ou d'un jet effectué par sa monture.

*Talents de discipline :* TODO



[[discipline_horror_stalker]]
=== Chasseur d'Horreurs

*Prérequis :* <<ranks,Novice>>, TODO

TODO

Un Chasseur d'Horreurs peut utiliser un point de Karma dans le cadre TODO


*Talents de discipline :* TODO



[[discipline_scout]]
=== Éclaireur

*Prérequis :* <<ranks,Novice>>, Perception d6+

Un Éclaireur ajoute +2 à ses jets de Discrétion, Perception, Recherche et Survie.
Ces bonus ne s'appliquent qu'en milieu sauvage.

Un Éclaireur peut utiliser un point de Karma dans le cadre d'un jet de Perception ou de Survie.

*Talents de discipline :* <<talent_chameleon,Caméléon>>, <<talent_trap_initiative,Esquive des pièges>>, <<talent_astral_sight,Vision astrale>>



[[discipline_sky_raider]]
=== Écumeur du ciel

*Prérequis :* <<ranks,Novice>>, Force d6+, Intimidation d6+

TODO

Un Écumeur du ciel utiliser un point de Karma dans le cadre d'un jet d'Intimidation, de Force, ou de n'importe quel jet effectué durant un combat de masse ayant lieu à bord d'un navire aérien.

*Talents de discipline :* <<talent_great_leap,Bondissement>>, <<talent_fireblood,Sang de feu>>, <<talent_wind_catcher,Vol plané>>



[[discipline_elementalist]]
=== Élémentaliste

*Prérequis :* <<ranks,Novice>>, Âme d6+, Survie d6+

Un Élémentaliste obtient le talent <<talent_spell_matrix,Matrice de Sorts>>.

Un Élémentaliste peut utiliser un point de Karma dans le cadre d'un jet de Survie.

*Talents de discipline :* <<talent_unshakeable_earth,Enracinement>>, <<talent_summoning,Invocation>>, <<talent_spell_matrix,Matrice de sorts>>, <<talent_astral_sight,Vision astrale>>



[[discipline_warrior]]
=== Guerrier

*Prérequis :* <<ranks,Novice>>, Combat d8+

Un Guerrier obtient un bonus de +1 à tous ses jets de dégâts au corps à corps.

Un Guerrier peut utiliser un point de Karma dans le cadre d'un jet de Combat ou de Connaissance (Batailles).

*Talents de discipline :* <<talent_temper_self,Endurcissement>>, <<talent_wood_skin,Peau de bois>>, <<talent_life_check,Ultime sursaut>>



[[discipline_illusionist]]
=== Illusionniste

*Prérequis :* <<ranks,Novice>>, Intellect d6+, Perception d6+

Un Illusioniste obtient le talent <<talent_spell_matrix,Matrice de Sorts>>.

Un Illusionniste peut utiliser un point de Karma dans le cadre d'un jet de Persuasion.

*Talents de discipline :* TODO



[[discipline_swordmaster]]
=== Maître d'armes

*Prérequis :* <<ranks,Novice>>, Combat d6+, Sarcasme d6+

Le Charisme d'un Maître d'armes est augmenté de 2.

Un Maître d'armes peut utiliser un point de Karma dans le cadre d'un jet de Combat ou de Sarcasme.

*Talents de discipline :* TODO



[[discipline_beastmaster]]
=== Maître des animaux

*Prérequis :* <<ranks,Novice>>, Vigueur d6+, Survie d6+

Les animaux n'attaquent pas le personnage, à moins qu'il ne les attaque en premier lieu ou qu'ils ne soient enragés pour une raison quelconque.

De plus, si un Maître des animaux passe un minimum de 10 minutes en compagnie d'un animal dont l'attitude envers lui est Neutre ou meilleure, cet animal peut s'attacher à lui et devenir son compagnon, si le Maître des animaux le désire.
Un compagnon animal accompagne fidèlement le personnage et a une attitude Serviable envers lui.
Au même moment, un Maître des animaux peut s'attacher à un nombre d'animaux maximum égal à son Rang.

Un Maître des animaux peut utiliser un point de Karma dans le cadre d'un jet effectué par un de ses compagnons animaux.

*Talents de discipline :* <<talent_chameleon,Caméléon>>, <<talent_claw_shape,Griffes>>, <<talent_animal_possession,Possession animale>>



[[discipline_air_sailor]]
=== Navigateur aérien

*Prérequis :* <<ranks,Novice>>, Agilité d6+, Manœuvre aérienne d6+

TODO

Un Navigateur aérien peut utiliser un point de Karma dans le cadre d'un jet de Manœuvre aérienne, ou de n'importe quel jet effectué durant un combat de masse ayant lieu à bord d'un navire aérien.

*Talents de discipline :* <<talent_great_leap,Bondissement>>, TODO, <<talent_wind_catcher,Vol plané>>



[[discipline_nethermancer]]
=== Nécromancien

*Prérequis :* <<ranks,Novice>>, Âme d6+, Intimidation d6+

Un Nécromancien obtient le talent <<talent_spell_matrix,Matrice de Sorts>>.

Un Nécromancien peut utiliser un point de Karma dans le cadre d'un jet d'Intimidation.

*Talents de discipline :* <<talent_lionheart,Cœur de lion>>, <<talent_summoning,Invocation>>, <<talent_spell_matrix,Matrice de sorts>>, <<talent_astral_sight,Vision astrale>>



[[discipline_wizard]]
=== Sorcier

*Prérequis :* <<ranks,Novice>>, Intellect d6+, Recherche d6+

Un Sorcier obtient le talent <<talent_spell_matrix,Matrice de Sorts>>.

Un Sorcier peut utiliser un point de Karma dans le cadre d'un jet de Recherche.

*Talents de discipline :* <<talent_evidence_analysis,Analyse des indices>>, <<talent_spell_matrix,Matrice de sorts>>, <<talent_book_memory,Mémoire des livres>>, <<talent_astral_sight,Vision astrale>>



[[discipline_troubadour]]
=== Troubadour

*Prérequis :* <<ranks,Novice>>, Intellect d6+, Persuasion d6+

Le Charisme d'un Troubadour est augmenté de 2.

Un Troubadour peut utiliser un point de Karma dans le cadre d'un jet de Persuasion, de Sarcasme ou de Recherche.

*Talents de discipline :* <<talent_emotion_song,Chant d'émotion>>, <<talent_speak_language,Glossolalie>>, <<talent_item_history,Histoire des objets>>, <<talent_winning_smile,Sourire ravageur>>



[[discipline_thief]]
=== Voleur

*Prérequis :* <<ranks,Novice>>, Agilité d6+, Discrétion d6+

Un Voleur ajoute +2 à tous ses jets de Discrétion.

Un Voleur peut utiliser un point de Karma dans le cadre d'un jet de Crochetage ou de Discrétion.

*Talents de discipline :* <<talent_surprise_strike,Attaque surprise>>, <<talent_great_leap,Bondissement>>, <<talent_trap_initiative,Esquive des pièges>>





[[talents]]
== Talents

Les talents sont des atouts étranges.
Tout personnage peut acquérir un talent du moment qu'il en satisfait les prérequis,
que ce talent figure dans la liste de ses talents de <<disciplines,discipline>>,
et qu'il trouve quelqu'un pour le lui apprendre.

[[talent_xxx]]
=== XXX

*Prérequis :* <<ranks,Novice>>, TODO

TODO

[[talent_evidence_analysis]]
=== Analyse des indices

*Prérequis :* <<ranks,Compagnon>>, Perception d6+

Le personnage peut dépenser un point de Karma pour obtenir un bonus à un jet de Perception égal à son Rang.

[[talent_surprise_strike]]
=== Attaque surprise

*Prérequis :* <<ranks,Gardien>>, Discrétion d10+

Une fois par combat, le personnage peut dépenser un point de Karma pour effectuer une _Attaque surprise_ (_Savage Worlds_ page 120), même si les circonstances ne devraient pas l'y autoriser.

[[talent_great_leap]]
=== Bondissement

*Prérequis :* <<ranks,Novice>>, Force d6+

Lors d'une course, le personnage peut ajouter un nombre de cases à son Allure égal à son Rang ×2.
Cette distance supplémentaire peut correspondre à un saut horizontal ou vertical.

[[talent_chameleon]]
=== Caméléon

*Prérequis :* <<ranks,Gardien>>, Discrétion d6+, Survie d8+

Le personnage peut dépenser un point de Karma pour obtenir un bonus à un jet de Discrétion égal à son Rang.

[[talent_emotion_song]]
=== Chant d'émotion

*Prérequis :* <<ranks,Novice>>, Âme d6+

Le personnage peut dépenser un point de Karma après avoir donné une représentation d'une durée d'une demie heure minimum,
au cours de laquelle il peut utiliser la (ou les) forme(s) artistique(s) de son choix.
Cependant, le personnage doit définir l'objet de la représentation, ainsi que le sentiment qu'il désire faire naître envers celui-ci.

À l'issue de cette représentation, le personnage effectue un jet d'Âme.
Si ce jet est réussi, le personnage gagne un bonus égal à son Rang à tout jet d'interaction sociale.
Ce bonus n'est valable que contre un spectateur ayant été présent jusqu'à la fin de la représentation,
et pour un jet faisant entrer en jeu à la fois le sentiment et l'objet de la représentation.

[[talent_lionheart]]
=== Cœur de lion

*Prérequis :* <<ranks,Novice>>, Âme d6+

Le personnage bénéficie d'un bonus de +2 sur ses jets de terreur.

[[talent_enchanting]]
=== Enchantement

*Prérequis :* <<ranks,Gardien>>, Arcanes: magie

Le personnage peut enchanter des objets magiques.
Voir la section <<enchanting,Enchantement>> pour davantage de détails.

[[talent_temper_self]]
=== Endurcissement

*Prérequis :* <<ranks,Gardien>>, Âme d8+, Vigueur d8+

Le personnage peut dépenser un certain nombre de points de Karma après avoir effectué un rituel d'une demie-heure.
Cela lui permet de gagner un bonus d'Armure égal au nombre de point de Karma dépensés,
avec un maximum égal à son Rang.
Le bonus d'Armure dure un nombre d'heures égal au Rang du personnage.

[[talent_unshakeable_earth]]
=== Enracinement

*Prérequis :* <<ranks,Novice>>, Force d6+

Le personnage peut dépenser un point de Karma pour gagner un bonus de +2 pour éviter d'être mis à terre.
Ce bonus perdure alors jusqu'à ce qu'un de ses pieds quitte le sol.

[[talent_trap_initiative]]
=== Esquive des pièges

*Prérequis :* <<ranks,Compagnon>>, Agilité d6+, Perception d6+

Le personnage peut dépenser un point de Karma pour avoir le droit d'effectuer un jet d'Agilité juste avant de subir les effets d'un piège.
Si le jet est réussi, le personnage échappe totalement au piège.

[[talent_flame_arrow]]
=== Flèche de feu

*Prérequis :* <<ranks,Compagnon>>, Âme d8+

Le personnage peut dépenser un point de Karma pour obtenir un bonus au jet de dégâts d'une attaque à distance.
Le bonus aux dégâts obtenu est égal au Rang du personnage.
Si l'arme utilisée est une arme de trait, la flèche tirée est détruite.

[[talent_forge_item]]
=== Forgeage

*Prérequis :* <<ranks,Novice>>, Réparation d6+

Le personnage gagne le talent <<talent_enchanting,Enchantement>>, même s'il n'en satisfait pas les prérequis.
Il ne peut cependant s'en servir que pour créer des objets magiques majoritairement en métal.
Il peut utiliser sa Compétence Réparation pour effectuer son <<enchanting,jet d'enchantement>>.

[[talent_speak_language]]
=== Glossolalie

*Prérequis :* <<ranks,Gardien>>, Intellect d6+

Après avoir entendu parler une langue pendant au minimum 1 minute, le personnage peut dépenser un point de Karma pour apprendre cette langue de manière permanente.

À la discrétion du MJ, le personnage peut réaffecter différemment les Promotions qu'il a précédement utilisées pour apprendre des langues.

[[talent_claw_shape]]
=== Griffes

*Prérequis :* <<ranks,Novice>>

Lorsqu'il effectue un jet de Combat à mains nues, le personnage est considéré comme armé.
De plus, il ajoute un bonus à ses jets de dégâts à mains nues égaux à son Rang.

[[talent_item_history]]
=== Histoire des objets

*Prérequis :* <<ranks,Compagnon>>, Perception d6+, Recherche d6+

Après avoir gardé auprès de lui un objet magique pendant une semaine, le personnage peut dépenser un point de Karma et effectuer un jet de Perception concernant cet objet.
Le personnage apprend une <<magic_items,connaissance de recherche>> de l'objet par succès et par Relance.

[[talent_summoning]]
=== Invocation

*Prérequis :* <<ranks,Compagnon>>, TODO

TODO

[[talent_spell_matrix]]
=== Matrice de sorts

*Prérequis :* <<ranks,Novice>>, TODO

TODO

[[talent_book_memory]]
=== Mémoire des livres

*Prérequis :* <<ranks,Gardien>>, Intellect d8+, Recherche d8+

Le personnage est considéré comme ayant toutes les connaissances existantes.
Il doit pour cela avoir parcouru au moins une fois un livre renfermant l'information recherchée.
Le personnage doit néanmoins dépenser un point de Karma pour se rappeler de l'information.

[[talent_wood_skin]]
=== Peau de bois

*Prérequis :* <<ranks,Novice>>, Vigueur d6

Le personnage peut dépenser un point de Karma pour bénéficier d'un bonus à sa Résistance égal à son Rang, pendant un nombre de rounds égal à son Rang.

[[talent_versatility]]
=== Polyvalence

*Prérequis :* <<ranks,Novice>>, <<race_human,Humain>>

Le personnage peut apprendre n'importe quel talent.
Le talent n'a pas besoin de figurer dans la liste de ses talents de discipline.
Cela mis à part, le personnage doit satisfaire tous les prérequis du talent désiré.
Il doit aussi toujours trouver un instructeur possédant ce talent et acceptant de le lui enseigner.

[[talent_animal_possession]]
=== Possession animale

*Prérequis :* <<ranks,Compagnon>>, Âme d6+

Le personnage peut dépenser un point de Karma pour posséder un animal ayant une attitude Amicale ou meilleure envers lui.
La possession a une durée maximale de Rang × 10 minutes.
Pendant tout le temps que dure la possession, le corps du personnage tombe en catatonie.

[[talent_fireblood]]
=== Sang de feu

*Prérequis :* <<ranks,Compagnon>>, Vigueur d6+

Le personnage peut dépenser un point de Karma pour effectuer un jet de guérison naturelle.
Dans le cadre de ce talent, ce jet ne lui prend qu'une action.
Ce jet ne bénéficie d'aucun bonus ou malus du aux conditions de convalescence.
Il souffre cependant des malus dus au blessures comme d'habitude.

[[talent_winning_smile]]
=== Sourire ravageur

*Prérequis :* <<ranks,Gardien>>, Persuasion d8+

Lors d'un jet de Persuasion, le personnage peut dépenser un point de Karma pour affecter un nombre d'Extras égal à son Rang.

[[talent_true_shot]]
=== Tir infaillible

*Prérequis :* <<ranks,Novice>>, Tir d6+

Le personnage peut dépenser un ou plusieurs points de Karma pour réduire les malus d'un jet de Tir.
Chaque point de Karma ainsi dépensé réduit le malus qui s'applique au jet de 2 points.
Plusieurs points de Karma peuvent être dépensés de cette manière, avec un maximum d'un par Rang.

Ce talent est une exception à la règle qui ne permet d'utiliser au maximum qu'un seul <<karma,point de Karma>> pour un jet.

[[talent_multishot]]
=== Tir multiple

*Prérequis :* <<ranks,Gardien>>, Tir d10+

Le personnage peut dépenser un ou plusieurs points de Karma pour augmenter la CdT de son arme à distance.
La CdT de l'arme pour le round est égale au nombre de points de Karma dépensés +1.
Le personnage peut dépenser au maximum un point de Karma par Rang de cette manière.

[[talent_life_check]]
=== Ultime sursaut

*Prérequis :* <<ranks,Compagnon>>, Âme d8+, Vigueur d8+

Lorsque le personnage sombre dans un État critique (_Savage Worlds_ page 116), mais avant d'effectuer le jet de Vigueur correspondant, il peut dépenser un point de Karma pour effectuer un jet d'Âme.
Le malus de blessure ne s'applique pas à ce jet d'Âme.
Si ce jet est réussi, il sort de cet État critique, avec son nombre maximal de blessures.
Sur une relance, le personnage guérit en plus une de ses blessures.

[[talent_astral_sight]]
=== Vision astrale

*Prérequis :* <<ranks,Novice>>, Perception d6+

Le personnage peut dépenser un point de Karma pour percevoir l'espace astral durant un nombre de minutes égal à son type de dé de Perception.

[[talent_wind_catcher]]
=== Vol plané

*Prérequis :* <<ranks,Gardien>>, Âme d6+

TODO





[[thread_magic]]
== Magie des sorts

TODO





[[magic_items]]
== Objets magiques

TODO

[[enchanting]]
=== Enchantement

TODO
